# Generated by Django 2.2.10 on 2021-06-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('lastName', models.CharField(max_length=200, verbose_name='Apellido')),
                ('carrera', models.CharField(max_length=200, verbose_name='Carrera')),
                ('grado', models.CharField(max_length=200, verbose_name='Grado')),
                ('grupo', models.CharField(max_length=200, verbose_name='Grupo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['-created'],
            },
        ),
    ]
