# Generated by Django 2.2.10 on 2021-07-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('carrera', models.CharField(max_length=100, verbose_name='Carrera')),
                ('grado', models.CharField(max_length=100, verbose_name='Grado | Grupo')),
                ('beca', models.CharField(max_length=100, verbose_name='Beca')),
            ],
        ),
    ]
