# Generated by Django 2.2.10 on 2021-07-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='beca',
            field=models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=100, verbose_name='Beca'),
        ),
    ]
